apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: srjm99silva@gmail.com

    privateKeySecretRef:
      name: letsencrypt-prod

    solvers:
      - selector:
          dnsNames:
            - geradorqrcode-srjm.uk
        http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: srjm-gateway-nginx
                namespace: qrcode-system
                kind: Gateway
                group: gateway.networking.k8s.io
                sectionName: http

      - selector:
          dnsNames:
            - grafana.geradorqrcode-srjm.uk
        http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: srjm-gateway-nginx
                namespace: qrcode-system
                kind: Gateway
                group: gateway.networking.k8s.io
                sectionName: grafana-http