apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tls-secret-reader
  namespace: qrcode-system
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - geradorqrcode-srjm-uk-tls
    verbs:
      - get